---
title: "ffball_EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
library(tidyverse)
```

```{r}
# Import data and select relevant features
file_dir <- paste(getwd(), "data", sep = "/../")
data <- paste(file_dir, "ADP&stats_2013-2021.csv", sep="/") %>% 
  read_delim(delim=",") %>%
  select(FirstName, LastName, Team, Position, Year, TeamPosRank, 
         ADP, PosRank1_ADP, PosRank2_ADP, PosAmbiguity, PPG_HalfPPR, GamesPlayed,
         everything()) # sorting columns
```

# ADP vs Points Per Game

```{r, message = F}
# ADP vs Points Scored Smoothed Means
data %>%
  filter(ADP <= 108, Position != "TE", GamesPlayed > 8) %>%
  ggplot(aes(x = ADP, y = PPG_HalfPPR, color = Position, group = Position)) +
  geom_point(size = 2, alpha = 0.8) +
  geom_smooth() +
  scale_color_manual(values = c("#EF8354", "#042A2B")) +
  theme_bw()
```

# Running Back Data - Busts

```{r}
# Running backs in first 5 rounds who played more than 8 games
rb_data <- data %>%
  filter(ADP <= 60, Position == "RB", GamesPlayed > 8)

# Fit linear regression model to evaluate
# Y_hat = 17.16584 - 0.13671 x ADP
rb_lin_reg_model <- lm(PPG_HalfPPR ~ ADP, data = rb_data)
summary(rb_lin_reg_model)

# Use linear regression model to get expected points 
rb_data <- rb_data %>%
  mutate(PPG_Expectation = predict.lm(rb_lin_reg_model, rb_data[, "ADP"]),
         .after = PPG_HalfPPR) %>%
  mutate(PPGvsExpectation = PPG_HalfPPR - PPG_Expectation) %>%
  mutate(Bust = ifelse(PPGvsExpectation < -4, T, F)) %>%
  arrange(PPGvsExpectation)

# Histogram of performance vs expectation
rb_data %>% 
  ggplot(aes(x = PPGvsExpectation)) +
  geom_histogram(bins = 15) +
  geom_vline(xintercept = -4, size = 1, color = "#A30015", linetype = 2) +
  labs(x = "PPG vs Expectation", y = "Count") +
  theme_bw()

# Scatterplot
rb_data %>%
  ggplot(aes(x = ADP, y = PPG_HalfPPR, color = Bust)) +
  geom_point(size = 3, alpha = 0.9) +
  geom_abline(intercept = 17.16584, slope = -0.13671, size = 1, color = "gray25") +
  scale_color_manual(values = c("#53131E", "#30C2FC")) +
  theme_bw()
```

# Wide Receiver Data - Busts

```{r}
# Wide receivers in first 5 rounds who played more than 8 games
wr_data <- data %>%
  filter(ADP <= 60, Position == "WR", GamesPlayed > 8)

# Fit linear regression model to evaluate
# Y_hat = 15.62736 - 0.08141 x ADP
wr_lin_reg_model <- lm(PPG_HalfPPR ~ ADP, data = wr_data)
summary(wr_lin_reg_model)

# Use linear regression model to get expected points 
wr_data <- wr_data %>%
  mutate(PPG_Expectation = predict.lm(wr_lin_reg_model, wr_data[, "ADP"]), 
         .after = PPG_HalfPPR) %>%
  mutate(PPGvsExpectation = PPG_HalfPPR - PPG_Expectation) %>%
  mutate(Bust = ifelse(PPGvsExpectation < -4, T, F)) %>%
  arrange(PPGvsExpectation)

# Histogram of performance vs expectation
wr_data %>% 
  ggplot(aes(x = PPGvsExpectation)) +
  geom_histogram(bins = 15) +
  geom_vline(xintercept = -4, size = 1, color = "#A30015", linetype = 2) +
  labs(x = "PPG vs Expectation", y = "Count") +
  theme_bw()

# Scatterplot
wr_data %>%
  ggplot(aes(x = ADP, y = PPG_HalfPPR, color = Bust)) +
  geom_point(size = 3, alpha = 0.9) +
  geom_abline(intercept = 15.62736, slope = -0.08141, size = 1, color = "gray25") +
  scale_color_manual(values = c("#53131E", "#30C2FC")) +
  theme_bw()
```


